# Generated by Django 3.0.6 on 2020-05-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_productimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThumbnailImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/products/thumbnail')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Products')),
            ],
        ),
    ]
