# Generated by Django 3.0.6 on 2020-05-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_productthumbnailimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
