# Generated by Django 3.0.6 on 2020-05-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_value',
        ),
    ]
